apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-08-27T05:26:09Z"
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Metrics-server
  name: metrics-server
  namespace: kube-system
  resourceVersion: "248705"
  selfLink: /api/v1/namespaces/kube-system/services/metrics-server
  uid: fccf7582-b5e7-47c3-964b-c1dc2c6549aa
spec:
  clusterIP: 10.101.102.105
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    k8s-app: metrics-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
